spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/booking_system
spring.datasource.username=postgres
spring.datasource.password=123456789

firebase.credentials.path=${firebase_credentials_path}
app.jwt.secret=${booking_system_jwt_secret_key}

supabase.url=${supabase_url_booking_system}
supabase.secret.service-key=${supabase_secret_service-key}
supabase.bucket-name=booking_system_user_profile

mail.sniper.api.key=${mail_sniper_api_key}