spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/booking_system
spring.datasource.username=postgres
spring.datasource.password=123456789

firebase.credentials.path=${firebase_credentials_path}
app.jwt.secret=${booking_system_jwt_secret_key}

