spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/booking_system
spring.datasource.username=postgres
spring.datasource.password=123456789

firebase.credentials.path=FIREBASE_CREDENTIALS_PATH

app.jwt.secret=JWT_SECRET_KEY